---
- name: Update group database
  group:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ system_groups }}"

- name: Update HPC user database
  user: 
    name: "{{ item.name }}"
    groups: "{{ item.groups |join(',')}}"
    append: yes 
    home: "/users/{{ item.name }}"
    createhome: no
    comment: "{{item.fullname}} ({{item.email}}) -- {{item.comment}}"
    state: "{{ item.state }}"
  with_items: "{{ system_users }}"

- name: Update email aliases
  template:
    src: aliases.j2
    dest: /etc/aliases
    owner: root
    group: root
    mode: 0644

- include: gpfs.yml
- include: gofirst.yml
- include: mountaineer.yml
